project:
  name: tree-sitter-jcl
  type: parser-generator
  language: javascript
  target: jcl-grammar

tracking:
  grammar_rules:
    path: grammar.js
    track:
      - rule_definitions
      - precedence_rules
      - token_definitions
      - externals
  
  test_files:
    path: test/**/*.js
    track:
      - test_cases
      - assertions
      - coverage
  
  query_patterns:
    path: queries/*.scm
    track:
      - query_definitions
      - capture_groups
      - predicates
  
  jcl_constructs:
    categories:
      - job_control:
          - JOB statements
          - EXEC statements
          - DD statements
      - procedures:
          - PROC definitions
          - PEND statements
          - procedure calls
      - conditionals:
          - IF/THEN/ELSE/ENDIF
          - COND parameters
      - includes:
          - INCLUDE statements
          - JCLLIB statements
      - datasets:
          - dataset names
          - dataset operations
          - temporary datasets
      - programs:
          - program invocations
          - utility programs
          - user programs

code_analysis:
  patterns:
    job_dependencies:
      description: Track job dependencies and execution flow
      query: |
        (job_statement
          name: (job_name) @job
          (exec_statement
            program: (program_name) @dependency))
    
    dataset_usage:
      description: Track dataset creation and usage
      query: |
        (dd_statement
          name: (dd_name) @dd
          dataset: (dataset_name) @dataset
          disposition: (disp_parameter) @usage)
    
    procedure_calls:
      description: Track procedure invocations
      query: |
        (exec_statement
          procedure: (proc_name) @procedure
          parameters: (parm_list) @params?)

development_tracking:
  tdd_compliance:
    enforce: true
    require_test_first: true
    minimum_coverage: 80
  
  grammar_evolution:
    track_changes: true
    version_rules: true
    document_decisions: true
  
  performance_metrics:
    parse_time: true
    memory_usage: true
    tree_size: true